# Generated by Django 3.0.7 on 2020-08-06 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200806_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='downloads',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='number_of_quiz',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
