# Generated by Django 3.0.7 on 2020-08-10 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_download_time_card_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download_time',
            name='card_pk',
        ),
        migrations.AddField(
            model_name='download_time',
            name='card',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='quiz.Card'),
        ),
    ]
