# Generated by Django 3.0.7 on 2020-08-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200810_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_time',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Card'),
        ),
    ]
