# Generated by Django 3.0.7 on 2020-08-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200810_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='hashtag',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
